services:
  personCatalogdb:
    image: mysql:8.0

  cachedb:
    image: redis:latest

  webApp:
   image: person-catalog-app:latest
   build:
      context: ./src/WebApp/person-catalog-app
      dockerfile: Dockerfile

  personcatalog.api:
    image: ${DOCKER_REGISTRY-}personcatalogapi
    build:
      context: .
      dockerfile: src/Services/PersonCatalog/PersonCatalog.API/Dockerfile

