services:
  personCatalogdb:
    image: mysql:8.0

  cachedb:
    image: redis:latest

  personcatalog.api:
    image: ${DOCKER_REGISTRY-}personcatalogapi
    build:
      context: src
      dockerfile: Services/PersonCatalog/PersonCatalog.API/Dockerfile
